name: vira_design
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  faker: ^1.2.1
  get: ^3.11.1
  # flutter_secure_storage: ^3.3.3
  backdrop: ^0.4.7 
  flutter_masked_text: ^0.7.0
  flare_flutter: ^1.7.1
  easy_localization: ^2.3.3
  easy_localization_loader: ^0.0.2
  equatable: ^1.2.5
  flutter_staggered_grid_view: ^0.3.2
  http: ^0.12.2
  shared_preferences: ^0.5.12+2
  intl: ^0.16.1
  dio: 3.0.10
  flutter_bloc: ^6.1.0
  multi_image_picker: ^4.7.12
  bloc: ^6.1.0
  google_fonts: ^1.1.1
 # flutter_swiper: ^1.1.6
  sse: ^3.5.0
  lazy_load_scrollview: ^1.1.0
  bottom_navy_bar: ^5.5.0
  neos_bottom_navigation: ^0.1.3
  material_floating_search_bar: ^0.2.2
  curved_navigation_bar: ^0.3.3
  flutter_swiper: ^1.1.6
  page_transition: "^1.1.6"
  convex_bottom_bar: ^2.6.0
  searchable_dropdown:
  flutter_custom_clippers: ^1.1.2
  flutter_icons: ^1.1.0
  pull_to_refresh: ^1.6.2
  carousel_slider: ^2.3.1
  wave: ^0.1.0
  infinite_listview: ^1.0.1+1
  # The following addsexport https_proxy="https://127.0.0.1:8123" the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/JosefinSans-VariableFont_wght.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Light.ttf
    - family: McLaren
      fonts:
        - asset: assets/fonts/McLaren-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-VariableFont_wght.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/avatars/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
